apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hifiberry-detector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: detector
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "100%"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: detector
    spec:
      restartPolicy: Always
      hostPID: true
      serviceAccountName: hifiberry-detector
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 10
      containers:
      - name: detector
        image: ghcr.io/mgoltzsche/hifiberry-detector:0.0.8 # kpt-set: ${image}:${version}
        env:
        - name: KEEP_RUNNING
          value: "true"
        - name: REBOOT_ON_CHANGE
          value: "true"
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-snd
          mountPath: /dev/snd
        - name: etc
          mountPath: /host/etc
        - name: boot
          mountPath: /boot
        - name: lib-modules
          mountPath: /lib/modules
      readinessProbe:
        exec:
          command:
          - cat /tmp/ready
        initialDelaySeconds: 3
        periodSeconds: 1
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
          type: Directory
      - name: etc
        hostPath:
          path: /etc
          type: Directory
      - name: boot
        hostPath:
          path: /boot
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
