apiVersion: apps/v1
kind: DaemonSet
metadata: # kpt-merge: /hifiberry-detector
  name: hifiberry-detector
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|DaemonSet|default|hifiberry-detector'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: detector
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "100%"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: detector
    spec:
      restartPolicy: Always
      hostPID: true
      serviceAccountName: hifiberry-detector
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 10
      containers:
      - name: detector
        image: ghcr.io/mgoltzsche/hifiberry-detector:0.1.0 # kpt-set: ${image}:${version}
        env:
        - name: KEEP_RUNNING
          value: "true"
        - name: REBOOT_ON_CHANGE
          value: "true"
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
        - name: dev
          mountPath: /dev
        - name: lib-modules
          mountPath: /lib/modules
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          initialDelaySeconds: 3
          periodSeconds: 1
      volumes:
      - name: host
        hostPath:
          path: /
          type: Directory
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
