apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hifiberry-detector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: detector
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "100%"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: detector
    spec:
      serviceAccountName: hifiberry-detector
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      hostPID: true
      containers:
      - name: detector
        image: ghcr.io/mgoltzsche/hifiberry-detector:0.0.2 # kpt-set: ${image}:${version}
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 29
        volumeMounts:
        - name: dev-snd
          mountPath: /dev/snd
        - name: etc
          mountPath: /host/etc
        - name: boot
          mountPath: /boot
          readOnly: true
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
          type: Directory
      - name: etc
        hostPath:
          path: /etc
          type: Directory
      - name: boot
        hostPath:
          path: /boot
          type: Directory
